"""rename address

Revision ID: 5786a57c052b
Revises: d89ca330b7b1
Create Date: 2024-08-24 12:23:02.012644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5786a57c052b'
down_revision = 'd89ca330b7b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###