"""rename department

Revision ID: d89ca330b7b1
Revises: bf85ba98d30b
Create Date: 2024-08-24 12:20:09.211170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd89ca330b7b1'
down_revision = 'bf85ba98d30b'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###